stages:
  - build
  - test

variables:
  RAILS_ENV: test
  DB_HOST: postgres
  POSTGRES_DB: ci_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "runner123"

lint:
  image: 'ruby:3.2.2'
  stage: build
  before_script:
    - apt-get update && apt-get install -y postgresql-client
    - bundle install
  script:
    - bundle exec rubocop

test:
  image: 'ruby:3.2.2'
  stage: test
  services:
    - postgres:15.3-alpine
  before_script:
    - apt-get update && apt-get install -y postgresql-client
    - bundle install
    - cp config/database-ci.yml config/database.yml
    - bundle exec rails db:create db:schema:load
  script: 
    - bundle exec rails spec