stages:
  - build
  - test

.base: &base
  image: 'ruby:3.2.2'
  before_script:
    - apt-get update && apt-get install -y postgresql-client
    - bundle install

.base_db: &base_db
  <<: *base
  variables:
    RAILS_ENV: test
    DB_HOST: postgres
    POSTGRES_DB: ci_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "runner123"
  services:
    - postgres:15.3-alpine
  before_script:
    - apt-get update && apt-get install -y postgresql-client
    - bundle install
    - cp config/database-ci.yml config/database.yml
    - bundle exec rails db:create db:schema:load

lint:
  <<: *base
  stage: build
  script:
    - bundle exec rubocop

brakeman:
  <<: *base
  stage: build
  script:
    - bundle exec brakeman --color

test:
  <<: *base_db
  stage: test
  script: 
    - bundle exec rails spec
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml
    when: on_success

system_test:
  <<: *base_db
  stage: test
  script: 
    - bundle exec rails spec:system
