require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: '3.0'
  Exclude:
    - 'config/**/*.rb'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'vendor/**/*'
  NewCops: disable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/concerns/*.rb'
    - 'config/routes.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4
