#!/bin/sh

psql -c "CREATE ROLE ${POSTGRES_USERNAME} WITH LOGIN PASSWORD '${POSTGRES_PASSWORD}';"
psql -c "GRANT CONNECT, TEMPORARY, CREATE ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USERNAME};"
psql -c "ALTER DATABASE ${POSTGRES_DB} OWNER TO ${POSTGRES_USERNAME};"
